---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: redis-operator
  name: ot-operators
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: ot-operators
  labels:
    control-plane: redis-operator
spec:
  selector:
    matchLabels:
      control-plane: redis-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: redis-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - -zap-log-level=info
        image: registry.cn-hangzhou.aliyuncs.com/leijianzhong/redis-operator:0.13.0
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      terminationGracePeriodSeconds: 10
      serviceAccountName: redis-operator
